package v1

import (
	_ "github.com/go-pharos/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @BasePath /v1

func Register(c *HTTPEndpoint) *echo.Echo {
	e := echo.New()

	g := e.Group("v1")
	g.GET("/device/list", c.DeviceList)
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	return e
}
