package v1

import (
	"github.com/Team8te/go-pharos/app/api/http/v1/device"
	"github.com/Team8te/go-pharos/app/api/http/v1/store"
	"github.com/Team8te/go-pharos/app/api/http/v1/ws"

	_ "github.com/Team8te/go-pharos/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @BasePath /v1
func Register(d *device.DeviceEndpoint, s *store.StoreEndpoint, ws *ws.WSEndpoint) *echo.Echo {
	e := echo.New()
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	g := e.Group("v1")
	g.GET("/device/list", d.DeviceList)

	g.GET("/store/file/list", s.StoreList)
	g.POST("/store/file/move", s.MoveFile)
	g.POST("/store/file/load", s.Load)

	g.GET("/ws", ws.Move)

	return e
}
